### ISSUE TITLE
Upload.sh from 'beniculturali' example fails to add the tries

### ISSUE THREAD

**Issue by costentz** [ag-sc/QueGG-web#3]
Running it gives the following error:
Exception in thread "main" org.apache.jena.query.QueryParseException: Line 4, column 9: Unresolved prefixed name: :date

**Comment by costentz** [comment]
After realizing that there was an italian version of the docker file I tried using that and the error is now

```
12:51:45.590 [main] DEBUG org.apache.jena.util.FileManager - Add location: LocatorFile
12:51:45.591 [main] DEBUG org.apache.jena.util.FileManager - Add location: ClassLoaderLocator
12:51:45.592 [main] DEBUG org.apache.jena.util.LocationMapper - Failed to find configuration: file:location-mapping.rdf;file:location-mapping.n3;file:location-mapping.ttl;file:etc/location-mapping.rdf;file:etc/location-mapping.n3;file:etc/location-mapping.ttl
12:51:45.592 [main] DEBUG org.apache.jena.util.FileManager - Add location: LocatorFile
12:51:45.593 [main] DEBUG org.apache.jena.util.FileManager - Add location: LocatorURL
12:51:45.593 [main] DEBUG org.apache.jena.util.FileManager - Add location: ClassLoaderLocator
12:51:45.596 [main] DEBUG org.apache.jena.riot.system.stream.JenaIOEnvironment - Failed to find configuration: location-mapping.ttl;location-mapping.rdf;location-mapping.n3;etc/location-mapping.rdf;etc/location-mapping.n3;etc/location-mapping.ttl
12:51:45.714 [main] DEBUG org.apache.jena.info - System architecture: 64 bit
12:51:45.723 [main] DEBUG org.apache.jena.info - System architecture: 64 bit
[INFO ] 2022-09-13 12:51:45.727 [main] QueGG - Starting QueGG with language parameter 'IT'
[INFO ] 2022-09-13 12:51:45.729 [main] QueGG - Input directory: /tmp/import
[INFO ] 2022-09-13 12:51:45.729 [main] QueGG - Output directory: /tmp/generatorout
key:scheda_di count:1
key:creazione_di count:2
turtle file now processing!!NounPPFrame-lexicon-creazione_di.ttl
turtle file now processing!!NounPPFrame-lexicon-scheda_di.ttl

# STDERR:
FileNotFoundException: /home/elahi/AHack/tamil/question-grammar-generator/src/main/resources/it/base/base.ttl (No such file or directory)
Usage: <[BE, BG, BN, CS, DA, DE, EL, EN, ES, ET, FI, FR, GA, HI, HR, HU, IT, JA, KO, LV, NL, PL, PT, RO, RU, TA, SK, SL, SV]> <input directory> <output directory>
```

**Comment by costentz** [comment]
I then tried creating the folder structure requested inside the container and getting the base.ttl file from https://github.com/fazleh2010/question-grammar-generator/blob/italian/src/main/resources/it/base/base.ttl, but that gave me this:
```
Exception in thread "main" org.apache.jena.query.QueryParseException: Encountered " "-" "- "" at line 4, column 10.
Was expecting one of:
<IRIref> ...
<PNAME_NS> ...
<PNAME_LN> ...
<VAR1> ...
<VAR2> ...
"a" ...
"(" ...
"!" ...
"^" ...

at org.apache.jena.sparql.lang.ParserSPARQL11.perform(ParserSPARQL11.java:100)
at org.apache.jena.sparql.lang.ParserSPARQL11.parse$(ParserSPARQL11.java:52)
at org.apache.jena.sparql.lang.SPARQLParser.parse(SPARQLParser.java:34)
at org.apache.jena.query.QueryFactory.parse(QueryFactory.java:147)
at org.apache.jena.query.QueryFactory.create(QueryFactory.java:79)
at org.apache.jena.query.QueryFactory.create(QueryFactory.java:52)
at org.apache.jena.query.ParameterizedSparqlString.asQuery(ParameterizedSparqlString.java:1435)
at org.apache.jena.query.ParameterizedSparqlString.asQuery(ParameterizedSparqlString.java:1422)
at grammar.sparql.SPARQLRequest.executeSelectQuery(SPARQLRequest.java:353)
at grammar.sparql.SPARQLRequest.getSparqlSelectResultList(SPARQLRequest.java:262)
at lexicon.LexicalEntryUtil.getReturnVariableConditionLabel(LexicalEntryUtil.java:644)
at grammar.generator.SentenceBuilderCopulativePP.interpretSentenceToken(SentenceBuilderCopulativePP.java:61)
at grammar.generator.SentenceBuilderImpl.generateFullSentencesForward(SentenceBuilderImpl.java:66)
at grammar.generator.NPPGrammarRuleGenerator.generateSentences(NPPGrammarRuleGenerator.java:33)
at grammar.generator.GrammarRuleGeneratorRoot.generate(GrammarRuleGeneratorRoot.java:244)
at QueGG.lambda$generateGrammarGeneric$6(QueGG.java:296)
at java.base/java.lang.Iterable.forEach(Unknown Source)
at QueGG.generateGrammarGeneric(QueGG.java:293)
at QueGG.generateByFrameType(QueGG.java:232)
at QueGG.loadInputAndGenerate(QueGG.java:187)
at QueGG.init(QueGG.java:172)
at QueGG.main(QueGG.java:92)
```
